# Generated by Django 3.2.9 on 2021-11-18 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0005_auto_20211118_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='date',
        ),
        migrations.RemoveField(
            model_name='meetup',
            name='organizer_email',
        ),
    ]
